# Generated by Django 3.2.3 on 2021-09-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_postforcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postforcomments',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='PostForComments',
        ),
    ]
