# Generated by Django 3.2.3 on 2021-09-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210925_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostByVisitor',
        ),
    ]
