# Generated by Django 3.2.3 on 2021-09-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_postbyvisitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postbyvisitor',
            name='post_club',
        ),
    ]
