# Generated by Django 3.2.3 on 2021-09-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_postbyvisitor_post_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postbyvisitor',
            name='post_image',
        ),
    ]
