# Generated by Django 3.2.3 on 2021-09-29 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_remove_postbyvisitor_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFromUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.TextField(max_length=255)),
                ('post_text', models.TextField(max_length=4095)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PostByVisitor',
        ),
    ]
