# Generated by Django 3.2.3 on 2021-09-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210929_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostFromUser',
        ),
    ]
