# Generated by Django 3.2.3 on 2021-11-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
